config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :posts
  resources :comments, except: [:index, :show]
  resources :ratings, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :integer          not null
#
# Indexes
#
#  index_comments_on_post_id  (post_id)
#

class Comment < ApplicationRecord
  include ActionView::Helpers::TextHelper
  belongs_to :post

  def body_display
    simple_format(body.html_safe, {}, sanitize: false)
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  published  :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  include ActionView::Helpers::TextHelper

  has_many :comments
  has_many :ratings

  scope :default_order, -> { order(:title) }
  scope :published, -> { where(published: true) }

  validate do
    errors[:title] << 'cannot contain the string fish' if 'fish'.in? titleeee
  end

  validates :title, presence: false, uniqueness: true

  def body_display
    simple_format(title.html_safe, {}, sanitize: false)
  end
end

app/models/rating.rb
# == Schema Information
#
# Table name: ratings
#
#  id         :integer          not null, primary key
#  stars      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :integer          not null
#
# Indexes
#
#  index_ratings_on_post_id  (post_id)
#

class Rating < ApplicationRecord
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]
  # GET /comments/new
  def new
    post = Post.find(params[:post_id])
    @comment = Comment.new(post: post)
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to @comment.post, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment.post, notice: 'Comment was successfully updated.'
    else
      render :new
    end
  end

  # DELETE /comments/1
  def destroy
    if @comment.destroy
      redirect_to @comment.post, notice: 'Comment was successfully deleted.'
    else
      render :new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:post_id, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all.default_order
  end

  # GET /posts/1
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body, :published)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:destroy]

  # GET /ratings/new
  def new
    post = Post.find(params[:post_id])
    @rating = Rating.new(post: post)
  end

  # POST /ratings
  def create
    @rating = Rating.new(rating_params)

    if @rating.save
      redirect_to @rating.post, notice: 'Rating was successfully created.'
    else
      render :new
    end
  end

  # DELETE /ratings/1
  def destroy
    @rating.destroy!
    redirect_to @rating.post, notice: 'Rating was deleted.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_rating
    @rating = Rating.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def rating_params
    params.require(:rating).permit(:post_id, :stars)
  end
end

app/views/comments/_form.html.erb
<%= form_for(@comment, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @comment.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h4>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group hidden">
    
      <%= f.label :post, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :post_id, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :body, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :body, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>

      <% if @comment.persisted? %>
        <%= link_to @comment, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
          Delete
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="page-header">
  <%= link_to post_path(@comment.post), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Editing comment</h1>
</div>

<%= render 'form' %>

app/views/comments/index.html.erb
<div class="page-header">
  <%= link_to new_comment_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Comment
  <% end %>
  <h1>Listing comments</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Post</th>
            <th>Body</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @comments.each do |comment| %>
        <%= content_tag :tr, id: dom_id(comment), class: dom_class(comment) do %>
                      <td><%= comment.post %></td>
                      <td><%= comment.body %></td>
                    <td><%= link_to 'Show', comment %></td>
          <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/comments/new.html.erb
<div class="page-header">
  <%= link_to post_path(@comment.post), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New comment</h1>
</div>

<%= render 'form' %>

app/views/comments/show.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_comment_path(@comment), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show comment</h1>
</div>

<dl class="dl-horizontal">
  <dt>Post:</dt>
  <dd><%= @comment.post %></dd>

  <dt>Body:</dt>
  <dd><%= @comment.body_display %></dd>

</dl>

app/views/home/index.html.erb
<h1>
  Home Page
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Super Blog", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if params[:controller] == 'posts' %>">
            <%= link_to 'Posts', posts_path %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container main-container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
      <%= f.label :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :body, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :body, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <div class="col-sm-offset-2 col-sm-10"> 
        <div class="checkbox">
          <label>
            <%= f.check_box :published %>
            Published      
          </label>
        </div>
      </div>
    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @post, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing post</h1>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="page-header">
  <%= link_to new_post_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Post
  <% end %>
  <h1>Listing posts</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Published</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <%= content_tag :tr, id: dom_id(post), class: dom_class(post) do %>
                      <td><%= post.title %></td>
                      <td><%= post.published %></td>
                    <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New post</h1>
</div>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_post_path(@post), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show post</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @post.title %></dd>

  <dt>Body:</dt>
  <dd><%= @post.body_display %></dd>

  <dt>Published:</dt>
  <dd><%= @post.published %></dd>

</dl>

<h1>
  Comments
</h1>
<hr>

<ul>
  <% @post.comments.each do |comment| %>
    <li class='comment-item'>
      <%= comment.body_display %>
      <%= link_to edit_comment_path(comment) do %>
        <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to new_comment_path(post_id: @post), class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-plus"></span>
  New Comment
<% end %>


<h1>
  Ratings
</h1>
<hr>

<ul>
  <% @post.ratings.each do |rating| %>
    <li class='comment-item'>
      <% (1..rating.stars).each do %>
        <span class="glyphicon glyphicon-star"></span>
      <% end %>
      <%= link_to rating, method: :delete, class: 'text-danger', data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to new_rating_path(post_id: @post), class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-plus"></span>
  New Rating
<% end %>

app/views/ratings/_form.html.erb
<%= form_for(@rating, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @rating.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h4>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group hidden">
    
      <%= f.label :post, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :post_id, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :stars, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.select :stars, [1,2,3,4,5], selected: 1, class: 'form-control' %>
      </div>
    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<div class="page-header">
  <%= link_to ratings_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @rating, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing rating</h1>
</div>

<%= render 'form' %>

app/views/ratings/index.html.erb
<div class="page-header">
  <%= link_to new_rating_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Rating
  <% end %>
  <h1>Listing ratings</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Post</th>
            <th>Stars</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @ratings.each do |rating| %>
        <%= content_tag :tr, id: dom_id(rating), class: dom_class(rating) do %>
                      <td><%= rating.post %></td>
                      <td><%= rating.stars %></td>
                    <td><%= link_to 'Show', rating %></td>
          <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
          <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/ratings/new.html.erb
<div class="page-header">
  <%= link_to post_path(@rating.post), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New rating</h1>
</div>

<%= render 'form' %>

app/views/ratings/show.html.erb
<div class="page-header">
  <%= link_to ratings_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_rating_path(@rating), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show rating</h1>
</div>

<dl class="dl-horizontal">
  <dt>Post:</dt>
  <dd><%= @rating.post %></dd>

  <dt>Stars:</dt>
  <dd><%= @rating.stars %></dd>

</dl>